name: Civilizations
main: com.kylantraynor.civilizations.Civilizations
version: 0.0.3-SNAPSHOT
softdepend: [dynmap, TitleManager, Towny, Vault, LWC, Quickshop, DraggyRPG]
commands:
  civilizationsanswer:
    description: Used to answer questions.
    permission: civilizations.answer
  civilizations:
    description: Access all Civilizations related commands.
    permission: civilizations.civilizations
    aliases: [civ]
  camp:
    description: Access all Camp commands.
    permission: civilizations.camp
  region:
    description: Access all Region commands.
    permission: civilizations.region
  selection:
    description: Access all commands related to the current selection.
    permission: civilizations.selection
  group:
    description: Access all group commands.
    permission: civilizations.group
  guild:
    description: Access all guild commands.
    permission: civilizations.guild
  townytown:
    description: Access all towny import related commands.
    permission: civilizations.towny
  plot:
    description: Access all plot commands.
    permission: civilizations.plot
    aliases: [civplot]
  stall:
    description: Access all marketstall commands.
    permission: civilizations.stall
  house:
    description: Access all house commands.
    permission: civilizations.house
    aliases: [h]
  blueprint:
    description: Access all blueprint commands.
    permission: civilizations.blueprint
    aliases: [bp]
  account:
    description: Access the account commands.
    permission: civilizations.account
    aliases: [civaccount,civacc]