name: Civilizations
main: com.kylantraynor.civilizations.Civilizations
version: 0.0.1
softdepend: [dynmap, TitleManager, Towny, Vault]
commands:
  civilizationsanswer:
    description: Used to answer questions.
    permission: civilizations.answer
  civilizations:
    description: Access all Civilizations related commands.
    permission: civilizations.civilizations
    aliases: [civ]
  camp:
    description: Access all Camp commands.
    permission: civilizations.camp
  selection:
    description: Access all commands related to the current selection.
    permission: civilizations.selection
  group:
    description: Access all group commands.
    permission: civilizations.group
  townytown:
    description: Access all towny import related commands.
    permission: civilizations.towny
  plot:
    description: Access all plot commands.
    permission: civilizations.plot
    aliases: [civplot]
  house:
    description: Access all house commands.
    permission: civilizations.house